theme:
  colorScheme: "#4fd8eb"
  layout: dark # dark | light | auto

favicon: "" # path( or url) of avatar such as /favicon.png

# Navigation Drawer 导航栏
drawer:
  menu: # add your entries here 在此处添加您的条目
    Home: # display text for "home page" 主页
      icon: home # mdui icon
      url: /
      home: true
    Categories: # catorgories 分类
      icon: folder
      url: /categories
    Tags: # tags 标签
      icon: bookmark
      url: /tags
    Archives: # archives 归档
      icon: archive
      url: /archives
    About: # about 关于
      icon: info
      url: /about

copyright: ""

# supports twikoo comment system
# see: https://twikoo.js.org/frontend.html
# this way only supports v0.2.0-beta, move to "comment" instead
# twikoo: 
#   enable: false
#   cdn: /js/twikoo.all.min.js # or use cdn such as https://cdn.bootcdn.net/ajax/libs/twikoo/1.6.31/twikoo.all.min.js
#   # twikoo settings:
#   envId: ""
#   region: '' 
#   path: location.pathname # will eval this, be careful
#   lang: 'zh-CN' 

comment:
  system: none # none | twikoo | gitalk
  twikoo:  # see: https://twikoo.js.org/frontend.html
    cdn: 
      js: /js/twikoo.all.min.js # or use cdn such as https://cdn.bootcdn.net/ajax/libs/twikoo/1.6.31/twikoo.all.min.js
    
    # twikoo settings:
    envId: "https://twikoo.tobylai.fun"
    region: '' # region, see twikoo documentation
    path: location.pathname # will eval this, be careful
    lang: 'zh-CN' 
  gitalk: # see https://github.com/gitalk/gitalk
    cdn:
      css: /css/gitalk.css
      js: /js/gitalk.min.js

    # gitalk settings:
    clientID: '' # GitHub Application Client ID
    clientSecret: '' # GitHub Application Client Secret
    repo: '' # GitHub repo
    owner: '' # GitHub repo owner
    admin: [] # GitHub repo owner and collaborators, only these guys can initialize github issues
    id: decodeURIComponent(location.pathname)# will eval this, be careful
    # this is like /2024/01/24/xxxxxxxxxx ,make sure the length < 50
    # Ensure uniqueness and length less than 50
    distractionFreeMode: false  # Facebook-like distraction free mode
    #proxy: 
    # you may need a reverse proxy to support cors, default url may not work in some places(such as cn)

# display in the card at the top of the page under the subtitle
display_index_top:
  text: "dev-mdsuper"
  avatar: "" # path( or url) of avatar such as /avatar.png

# assets
mdui:
  css: /css/mdui_2.0.3/mdui.css
  js: /css/mdui_2.0.3/mdui.global.js

# install https://github.com/wzpan/hexo-generator-search and configure it following the readme
search:
  enable: true
  xml: /search.xml # only supports xml